### ISSUE TITLE
The utility of 1vs1 with 5-face dices

### ISSUE THREAD

**Issue by DiligentPanda** [thomasahle/snyd#1]
Hi, thank you for your helpful codes and results. I am recently learning Counterfactual Regret Minimization algorithm and experimenting with 1vs1 Liar's dice. 

![image](https://user-images.githubusercontent.com/25078430/148644625-9aa74a5a-7674-47e7-a185-d79972207066.png)

This value might be a typo. According to the experiment and formula provided by [this paper](http://www.cs.ubbcluj.ro/~studia-i/contents/2014-macs/04Burcsi.pdf), the correct one might be -3/25=-0.12.

I also notice that you program a marvelous Dudo AI handling multiple-dice cases. Is it possible to provide some references in that repo? This is really a fascinating field!

**Comment by thomasahle** [comment]
You are right! `-3/25` is indeed the value from https://github.com/thomasahle/snyd/blob/master/outputs/11_5.normal I just transcribed it wrongly. I've fixed it now. Thanks!

Where did you find the value in Burcsi's paper?

I'm writing a blog post about how the multi-dice dudo AI works. Would you be interested in reading a draft?

**Comment by DiligentPanda** [comment]
![image](https://user-images.githubusercontent.com/25078430/148689305-73fd60b9-6e51-4f64-a441-3c8eb0993c14.png)

Actually I check the formula in theorem 2.1. The winning probability  of player 2 is 14/25. So the expected utility of player 1 would be 1*11/25+(-1)*14/25=-3/25.

Of course! Looking forward to your post!
